/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HoneyBootstrapStyle {
    }
}
declare global {
    interface HTMLHoneyBootstrapStyleElement extends Components.HoneyBootstrapStyle, HTMLStencilElement {
    }
    var HTMLHoneyBootstrapStyleElement: {
        prototype: HTMLHoneyBootstrapStyleElement;
        new (): HTMLHoneyBootstrapStyleElement;
    };
    interface HTMLElementTagNameMap {
        "honey-bootstrap-style": HTMLHoneyBootstrapStyleElement;
    }
}
declare namespace LocalJSX {
    interface HoneyBootstrapStyle {
    }
    interface IntrinsicElements {
        "honey-bootstrap-style": HoneyBootstrapStyle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "honey-bootstrap-style": LocalJSX.HoneyBootstrapStyle & JSXBase.HTMLAttributes<HTMLHoneyBootstrapStyleElement>;
        }
    }
}
