/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HoneyBoostrapStyle {
    }
}
declare global {
    interface HTMLHoneyBoostrapStyleElement extends Components.HoneyBoostrapStyle, HTMLStencilElement {
    }
    var HTMLHoneyBoostrapStyleElement: {
        prototype: HTMLHoneyBoostrapStyleElement;
        new (): HTMLHoneyBoostrapStyleElement;
    };
    interface HTMLElementTagNameMap {
        "honey-boostrap-style": HTMLHoneyBoostrapStyleElement;
    }
}
declare namespace LocalJSX {
    interface HoneyBoostrapStyle {
    }
    interface IntrinsicElements {
        "honey-boostrap-style": HoneyBoostrapStyle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "honey-boostrap-style": LocalJSX.HoneyBoostrapStyle & JSXBase.HTMLAttributes<HTMLHoneyBoostrapStyleElement>;
        }
    }
}
